"""Generate CLAUDE.md context files from stored memories."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from claude_memory.config import MemoryConfig, project_path_to_claude_dir
from claude_memory.db import MemoryDB
from claude_memory.models import Memory, MemoryType, ProjectContext
from claude_memory.search import MemorySearch
from claude_memory.utils import format_duration, project_name_from_path


# ── Internal helpers ────────────────────────────────────────────────────────

_MAX_ITEMS_PER_SECTION = 10


def _bullet(text: str) -> str:
    """Format a single bullet point, collapsing to one line."""
    return f"- {text.strip()}"


def _section(title: str, items: list[str]) -> str:
    """Render a markdown section. Returns empty string when *items* is empty."""
    if not items:
        return ""
    capped = items[:_MAX_ITEMS_PER_SECTION]
    body = "\n".join(_bullet(item) for item in capped)
    return f"## {title}\n\n{body}\n"


def _memory_one_liner(memory: Memory) -> str:
    """Condense a memory into a single descriptive line."""
    line = memory.title
    if memory.content and memory.content != memory.title:
        # Append a short content excerpt when it adds useful detail.
        extra = memory.content.replace("\n", " ").strip()
        if len(extra) > 120:
            extra = extra[:117] + "..."
        line = f"**{memory.title}** — {extra}"
    return line


# ── Generator ───────────────────────────────────────────────────────────────


class ClaudemdGenerator:
    """Build and write CLAUDE.md context files from the memory store."""

    def __init__(self, db: MemoryDB, search: MemorySearch):
        self.db = db
        self.search = search

    # ── Public API ───────────────────────────────────────────────────────

    def generate_project_context(self, project_path: str) -> str:
        """Generate the full CLAUDE.md markdown content for *project_path*."""
        project_name = project_name_from_path(project_path)
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        sections: list[str] = []

        # Header
        sections.append(
            f"# {project_name}\n\n"
            f"> Auto-generated by claude-memory on {now_str}. "
            "Do not edit manually — changes will be overwritten.\n"
        )

        # 1. Key Decisions
        decisions = self.search.by_type(project_path, MemoryType.DECISION, limit=_MAX_ITEMS_PER_SECTION)
        sections.append(_section("Key Decisions", [_memory_one_liner(m) for m in decisions]))

        # 2. Active TODOs
        todos = self.search.by_type(project_path, MemoryType.TODO, limit=_MAX_ITEMS_PER_SECTION)
        sections.append(_section("Active TODOs", [_memory_one_liner(m) for m in todos]))

        # 3. Code Patterns & Conventions
        patterns = self.search.by_type(project_path, MemoryType.PATTERN, limit=_MAX_ITEMS_PER_SECTION)
        sections.append(_section("Code Patterns & Conventions", [_memory_one_liner(m) for m in patterns]))

        # 4. Recent Sessions (last 5 summaries)
        recent_sessions = self.db.get_recent_sessions(project_path=project_path, limit=5)
        session_lines: list[str] = []
        for sess in recent_sessions:
            date_str = sess.started_at.strftime("%Y-%m-%d")
            duration_str = format_duration(sess.duration_minutes) if sess.duration_minutes else "?"
            summary = sess.summary_text.replace("\n", " ").strip() if sess.summary_text else "No summary"
            if len(summary) > 120:
                summary = summary[:117] + "..."
            branch_info = f" (`{sess.git_branch}`)" if sess.git_branch else ""
            session_lines.append(f"{date_str}{branch_info} [{duration_str}]: {summary}")
        sections.append(_section("Recent Sessions", session_lines))

        # 5. User Preferences
        preferences = self.search.by_type(project_path, MemoryType.PREFERENCE, limit=_MAX_ITEMS_PER_SECTION)
        sections.append(_section("User Preferences", [_memory_one_liner(m) for m in preferences]))

        # 6. Known Issues & Solutions
        issues = self.search.by_type(project_path, MemoryType.ISSUE, limit=_MAX_ITEMS_PER_SECTION)
        solutions = self.search.by_type(project_path, MemoryType.SOLUTION, limit=_MAX_ITEMS_PER_SECTION)
        issue_lines: list[str] = []
        for m in issues:
            issue_lines.append(f"🐛 {_memory_one_liner(m)}")
        for m in solutions:
            issue_lines.append(f"✅ {_memory_one_liner(m)}")
        sections.append(_section("Known Issues & Solutions", issue_lines))

        # Assemble – drop empty sections
        body = "\n".join(s for s in sections if s)
        return body

    def build_project_context(self, project_path: str) -> ProjectContext:
        """Build a structured ``ProjectContext`` model from stored data."""
        project_name = project_name_from_path(project_path)
        total_sessions = self.db.count_sessions(project_path=project_path)
        total_memories = self.db.count_memories(project_path=project_path)

        recent_sessions = self.db.get_recent_sessions(project_path=project_path, limit=1)
        last_session_at = recent_sessions[0].started_at if recent_sessions else None

        decisions = self.search.by_type(project_path, MemoryType.DECISION, limit=_MAX_ITEMS_PER_SECTION)
        todos = self.search.by_type(project_path, MemoryType.TODO, limit=_MAX_ITEMS_PER_SECTION)
        patterns = self.search.by_type(project_path, MemoryType.PATTERN, limit=_MAX_ITEMS_PER_SECTION)

        return ProjectContext(
            project_path=project_path,
            project_name=project_name,
            total_sessions=total_sessions,
            total_memories=total_memories,
            last_session_at=last_session_at,
            key_decisions=[m.title for m in decisions],
            active_todos=[m.title for m in todos],
            common_patterns=[m.title for m in patterns],
        )

    def write_to_memory_dir(self, project_path: str, config: MemoryConfig | None = None) -> Path:
        """Write context to ``~/.claude/projects/<PATH>/memory/context.md``."""
        claude_dir = project_path_to_claude_dir(project_path, config)
        memory_dir = claude_dir / "memory"
        memory_dir.mkdir(parents=True, exist_ok=True)
        dest = memory_dir / "context.md"
        content = self.generate_project_context(project_path)
        dest.write_text(content, encoding="utf-8")
        return dest

    def write_to_project_root(self, project_path: str) -> Path:
        """Write context to ``<project>/CLAUDE.md``."""
        dest = Path(project_path) / "CLAUDE.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        content = self.generate_project_context(project_path)
        dest.write_text(content, encoding="utf-8")
        return dest

    def render_to_string(self, project_path: str) -> str:
        """Return the rendered CLAUDE.md content without writing to disk."""
        return self.generate_project_context(project_path)
